[package]
name = "os"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = "0.13.0"
buddy_system_allocator = "0.6"
volatile = { version = "0.6.1", features = ["derive"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
bitflags = "2.9.0"
